# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QApplication, QLabel
from PyQt5.QtCore import QRect, Qt
from PyQt5.QtGui import QImage, QPixmap, QPainter, QPen, QGuiApplication
import cv2
import sys
point = (-1, -1)
size = (0, 0)
from IntegrateApp import global_var


class MyLabel(QLabel):
    x0 = 0
    y0 = 0
    x1 = 0
    y1 = 0
    flag = False

    # 鼠标点击事件
    def mousePressEvent(self, event):
        self.flag = True
        self.x0 = event.x()
        self.y0 = event.y()

    # 鼠标释放事件
    def mouseReleaseEvent(self, event):
        self.flag = False

    # 鼠标移动事件
    def mouseMoveEvent(self, event):
        if self.flag:
            self.x1 = event.x()
            self.y1 = event.y()
            self.update()

    # 绘制事件
    def paintEvent(self, event):
        global point, size
        global_var._init()
        super().paintEvent(event)
        point = (min(self.x0, self.x1),  min(self.y0, self.y1))
        width = abs(self.x1 - self.x0)
        height = abs(self.y1 - self.y0)
        size = (width, height)
        rect = QRect(point[0], point[1], width, height)
        painter = QPainter(self)
        painter.setPen(QPen(Qt.red, 2, Qt.SolidLine))
        painter.drawRect(rect)
        global_var.set_value('point', point)
        global_var.set_value('size', size)



class My_Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(My_Ui_MainWindow,self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1438, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_button.setGeometry(QtCore.QRect(130, 620, 75, 23))
        self.select_button.setObjectName("select_button")
        self.img_label = MyLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(90, 70, 512, 512))
        self.img_label.setMaximumSize(QtCore.QSize(512, 512))
        self.img_label.setObjectName("img_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 70, 512, 512))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar_file = QtWidgets.QMenuBar(MainWindow)
        self.menubar_file.setGeometry(QtCore.QRect(0, 0, 1438, 23))
        self.menubar_file.setObjectName("menubar_file")
        self.menu = QtWidgets.QMenu(self.menubar_file)
        self.menu.setObjectName("menu")
        self.menuhelp = QtWidgets.QMenu(self.menubar_file)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar_file)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionquit)
        self.menubar_file.addAction(self.menu.menuAction())
        self.menubar_file.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "my"))
        self.select_button.setText(_translate("MainWindow", "RUN"))
        self.img_label.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionquit.setText(_translate("MainWindow", "quit"))


    def handleCalc(self):
        print(123)
