# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1655, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(50, 580, 91, 31))
        self.run_button.setObjectName("run_button")
        self.detected_label = QtWidgets.QLabel(self.centralwidget)
        self.detected_label.setGeometry(QtCore.QRect(530, 30, 512, 512))
        self.detected_label.setObjectName("detected_label")
        self.img_label = QtWidgets.QLabel(self.centralwidget)
        self.img_label.setGeometry(QtCore.QRect(0, 30, 512, 512))
        self.img_label.setMaximumSize(QtCore.QSize(512, 512))
        self.img_label.setObjectName("img_label")
        self.track_label = QtWidgets.QLabel(self.centralwidget)
        self.track_label.setGeometry(QtCore.QRect(1050, 30, 512, 512))
        self.track_label.setObjectName("track_label")
        self.track_button = QtWidgets.QPushButton(self.centralwidget)
        self.track_button.setGeometry(QtCore.QRect(330, 580, 81, 31))
        self.track_button.setObjectName("track_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar_file = QtWidgets.QMenuBar(MainWindow)
        self.menubar_file.setGeometry(QtCore.QRect(0, 0, 1655, 23))
        self.menubar_file.setObjectName("menubar_file")
        self.menu = QtWidgets.QMenu(self.menubar_file)
        self.menu.setObjectName("menu")
        self.menuhelp = QtWidgets.QMenu(self.menubar_file)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar_file)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionopen_folder = QtWidgets.QAction(MainWindow)
        self.actionopen_folder.setObjectName("actionopen_folder")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionopen_folder)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionquit)
        self.menubar_file.addAction(self.menu.menuAction())
        self.menubar_file.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "my"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.detected_label.setText(_translate("MainWindow", "TextLabel"))
        self.img_label.setText(_translate("MainWindow", "TextLabel"))
        self.track_label.setText(_translate("MainWindow", "TextLabel"))
        self.track_button.setText(_translate("MainWindow", "Track"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionquit.setText(_translate("MainWindow", "quit"))
        self.actionopen_folder.setText(_translate("MainWindow", "open folder"))
